### ISSUE TITLE
Cloudfare error : Error parsing form fields

### ISSUE THREAD

**Issue by johndodev** [softavis/flysystem-cloudflare-bundle#1]
Hello,

I have an error in the cloudfare response : Error parsing form fields

Cloudfare error is not very clear and lack documentation, but after multiple dd() and tries, I manage to get it working by changing `'body' => $formData->toIterable(),`  to `'body' => $formData->bodyToString(),` in `oftavis\flysystem-cloudflare\src\Client.php`.

I don't really know why, it's from Symfony doc : https://symfony.com/doc/current/http_client.html#uploading-data (look for "toString()").

Also, not directly related, but I saw your two repo, cloudfare and CloudfareBundle. The first one also have documentation for symfony. I suppose you did this one first, then create the bundle. It's a litle but confusing, maybe you should redirect here only for symfony users.

Should I make a PR ?

**Comment by naskoff** [comment]
Hi @johndodev 
Base on error message, you don't provide valid json data to cloudflare, ie your form body must contain this schema -> https://developers.cloudflare.com/api/operations/cloudflare-images-upload-an-image-via-url#request-body .
Are you using headers with formData, ie 'headers' => $formData->getPreparedHeaders()->toArray() to request?

Maybe if you share some code, i will be more helpful.

PP flysystem-cloudflare is basic library to work with cloudflare, this repo (flysystem-cloudflare-bundle) is just wrapper - have symfony bundle configuration and flex recipe for fast using. Everyone is free to use main library or use this bundle. 👍

**Comment by johndodev** [comment]
Ah, I didn't see this doc, it's interesting.

But, it's not really me providing anything, I'm using Flysystem, which use this library adapter, the error is calling $flysystemOperator->write(...);

I was talking about an eror on this line : https://github.com/softavis/flysystem-cloudflare/blob/master/src/Client.php#L169 

(But yes actually it's not in this repo but on the adapter repo, my bad).

The form datas is ok, it's just the way the symfony client send the datas apparenlty. Again, it's actually working, by just changing one line in the file. I can't do anything in my own code to make it works at this level.

**Comment by naskoff** [comment]
Aha, i see. In that case, you don't need this "bundle" but only other repository?

That line you marked is not the reason for error message, error message actually came from cloudflare api.
For that I think you don't actually send any file content for some reason.

Also, again if you share your code or some example how you use it, i can be more helpful i think.

**Comment by johndodev** [comment]
I use this bundle actually, for convenience. 

The initial error message was triggered by https://github.com/softavis/flysystem-cloudflare/blob/master/src/CloudflareAdapter.php#L67 
It was something like "Unable to write file [...] : got a 400 bad request response" or something like that. 
I wanted to retrieve cloudfare error so I made a dd() of the response in the client, something like 

```
$response = $this->client->request(self::METHOD_POST, self::API_VERSION, [
    'headers' => $formData->getPreparedHeaders()->toArray(),
    'body' => $formData->bodyToString(),
])->toArray(false);
dd($response). 
```
Then I saw "Error parsing form fields" somewhere.

I don't have much code to show because it's just a few lines, and if I switch the adapter in the flysystem.yaml with the local one for example, it's working. I don't have specific code for cloudfare. It's something like 

```
// somewhere in a Uploader service, flysystemOperator is injected
public function uploadImage(UploadedFile $file): string
{
    $path = 'storage/' . date('Y/') . uniqid() . '.' . $file->guessExtension();
    $this->flysystemOperator->write($path, file_get_contents($file->getPathname())); 
}
```
Flysystem config is also very simple, with all four env variable of this bundle, everything is working fine if the client send the body as string instead of iterable. 
```
storage.cloudfare:
    adapter: 'cloudflare'
    options:
        token: '%env(CLOUDFLARE_ACCESS_TOKEN)%'
        accountId: '%env(CLOUDFLARE_ACCOUNT_ID)%'
        accountHash: '%env(CLOUDFLARE_ACCOUNT_HASH)%'
        variantName: '%env(CLOUDFLARE_VARIANT_NAME)%'
```

**Comment by naskoff** [comment]
Oh, yea, this is something actually helpful. 
Can you check your API KEY permissions as shows [here](https://github.com/softavis/flysystem-cloudflare/issues/3#issuecomment-2041068990)

**Comment by johndodev** [comment]
I used the default permission when enabling images storage on cloudfare : 
![image](https://github.com/user-attachments/assets/56d1ecbc-4ac2-429b-87f2-93804067ec23)

Also, since it's working when I change the line in the client.php, I already successfully upladed image : 
![image](https://github.com/user-attachments/assets/1e2ffe8b-0a50-4c23-bb6b-2782f2ee84ab)

**Comment by naskoff** [comment]
Sorry, I just now actually understand what you mean.
I think with newer version "bodyToIterable" is not recommended anymore.
PR's are welcome, or I will update adapter later these days anyway.

**Comment by johndodev** [comment]
It's alright, I know it's pretty dark and cloudfare do not mention anything about "streaming" form datas, network related. I'm closing and do a quick PR with github editor, since it's just one line.
Thanks for being reactive.
